title: Kaleidoscope
author:
  name: 'UW MRSEC'
  email: david.gagnon@wisc.edu
taxonomies:
  - grades
  - 'resource type'
  - time
  - 'page type'
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
